#!/command/with-contenv bashio
# shellcheck shell=bash

set -eEuo pipefail

# Пути к основным файлам и директориям
CONFIG_DIR="/config"
CONFIG_FILE="${CONFIG_DIR}/redis.conf"
TMP_FILE="${CONFIG_FILE}.tmp"

DATA_DIR="/data"
LOG_DIR="/var/log/redis"

# Информация об аддоне
ADDON_VERSION="$(bashio::app.version)"
ADDON_NAME="$(bashio::app.name)"

# Логирование
# Вывод базовой информации о запуске аддона
bashio::log "============================================="
bashio::log.blue "=== ${ADDON_NAME} ==="
bashio::log.blue "=== Version: ${ADDON_VERSION} ==="
bashio::log.green "Init started at: $(date '+%Y-%m-%d %H:%M:%S')"

# Проверка конфигурации
# Чтение и проверка параметров из options/schema

maxmemory="$(bashio::config 'maxmemory')"
maxmemory_policy="$(bashio::config 'maxmemory_policy')"

# Проверка maxmemory — число с суффиксом (mb, gb) или без
if ! [[ "${maxmemory}" =~ ^[0-9]+(mb|gb)?$ ]]; then
    bashio::log.red "Invalid maxmemory: ${maxmemory}"
    exit 1
fi

# Проверка политики вытеснения — только допустимые значения
case "${maxmemory_policy}" in
    noeviction|allkeys-lru|allkeys-lfu|allkeys-random|volatile-lru|volatile-lfu|volatile-random|volatile-ttl)
        ;;
    *)
        bashio::log.red "Invalid maxmemory_policy: ${maxmemory_policy}"
        exit 1
        ;;
esac

# Подготовка директорий
# Создание директорий, необходимых для работы Redis
bashio::log "Preparing runtime directories..."

mkdir -p "${DATA_DIR}"
mkdir -p "${LOG_DIR}"

chmod 755 "${DATA_DIR}"
chmod 755 "${LOG_DIR}"

# Генерация конфигурации
# Если пользовательского конфига нет — создаём дефолтный
bashio::log "Generating redis.conf..."

{
    echo "# Redis configuration"
    echo "# Generated by ${ADDON_NAME} at $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""

    # Сеть
    echo "bind 0.0.0.0"
    echo "port 6379"
    echo "protected-mode no"
    echo ""

    # Память
    echo "maxmemory ${maxmemory}"
    echo "maxmemory-policy ${maxmemory_policy}"
    echo ""

    # Персистентность выключена — Redis используется как кэш
    echo "save \"\""
    echo "appendonly no"
    echo ""

    # Логи
    echo "logfile \"\""
    echo "loglevel notice"
    echo ""

    # Рабочая директория
    echo "dir ${DATA_DIR}"

} > "${TMP_FILE}"

# Атомарная замена конфигурационного файла
mv "${TMP_FILE}" "${CONFIG_FILE}"
chmod 644 "${CONFIG_FILE}"

bashio::log.green "Configuration generated successfully"

bashio::log "\033[0;34mMaxmemory: \033[0;32m${maxmemory}\033[0m"
bashio::log "\033[0;34mMaxmemory policy: \033[0;32m${maxmemory_policy}\033[0m"

# Завершение
# Init завершает работу после подготовки окружения
bashio::log.green "Init completed successfully"
