name: Simple DLNA
description: "Lightweight DLNA server based on ReadyMedia"
version: "0.2.17"
slug: simple_dlna
url: "https://github.com/alekslegkih/ha-addons/tree/main/simple_dlna"
arch:
  - amd64
  - aarch64
image: ghcr.io/alekslegkih/simple_dlna
startup: application
boot: auto
init: false
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
devices:
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdb3
  - /dev/sdc3
  - /dev/sdd1
  - /dev/sde3
  - /dev/sdf3
  - /dev/sdb4
  - /dev/sdc4
  - /dev/sdd4
  - /dev/sde4
  - /dev/sdf4
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
  - /dev/mmcblk0
  - /dev/mmcblk1
  - /dev/fuse
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
host_network: true
map:
  - addon_config:rw
  - media:rw
options:
  device: ""
  media_dir: "dlna"
  friendly_name: "Simple DLNA"
  log_level: "error"
schema:
  device: "str"
  media_dir: str
  friendly_name: str
  log_level: list(off|fatal|error|warn|info|debug)
panel_icon: mdi:dlna
panel_title: "DLNA browser"
ports:
  8200/tcp: 8200
ports_description:
  8200/tcp: Static server
ingress: true
ingress_stream: true
ingress_port: 8899

