name: "Caddy Proxy"
description: "Caddy reverse-proxy"
version: "0.2.3"
slug: "caddy_proxy"

url: "https://github.com/alekslegkih/ha-addons/tree/main/caddy_proxy"
image: ghcr.io/alekslegkih/caddy_proxy-dev

arch:
  - aarch64
  - amd64

startup: services
boot: auto
init: false

map:
  - addon_config:rw
  - ssl:ro

schema:
  log_level: list(trace|debug|info|warning|error|fatal)
options:
  log_level: "info"

ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: "HTTP"
  443/tcp: "HTTPS"

panel_icon: mdi:arrow-decision
panel_title: "Caddy proxy browser"

ingress: true
ingress_port: 5000

