name: "Backup Sync to USB"
description: "Automatically copies Home Assistant backups to connected USB storage"
version: "0.6.4"
slug: "backup_sync"
url: "https://github.com/alekslegkih/ha-addons/tree/main/backup_sync"
arch:
  - amd64
  - aarch64
image: ghcr.io/alekslegkih/backup_sync-dev
startup: application
boot: auto
init: false
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
devices:
  - /dev/sda
  - /dev/sda1
  - /dev/sda2
  - /dev/sda3
  - /dev/sda4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/sdb
  - /dev/sdb1
  - /dev/sdb2
  - /dev/sdb3
  - /dev/sdb4
  - /dev/sdb5
  - /dev/sdb6
  - /dev/sdc
  - /dev/sdc1
  - /dev/sdc2
  - /dev/sdc3
  - /dev/sdc4
  - /dev/sdd
  - /dev/sdd1
  - /dev/sdd2
  - /dev/sdd3
  - /dev/sdd4
  - /dev/sde
  - /dev/sde1
  - /dev/sde2
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n1p3
  - /dev/mmcblk0
  - /dev/mmcblk0p1
  - /dev/mmcblk0p2
  - /dev/mmcblk0p3
  - /dev/mmcblk1
  - /dev/mmcblk1p1
  - /dev/mmcblk1p2
  - /dev/mmcblk1p3
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
map:
  - app_config:rw
  - backup:ro
options:
  device: ""
  max_copies: 7
  sync_exist_start: false
schema:
  device: "str"
  max_copies: "int"
  sync_exist_start: "bool"
panel_icon: mdi:cloud-upload-outline
panel_title: "Backup browser"
ingress: true
ingress_stream: true
ingress_port: 8899
