name: TG → Transmission
description: "Receive torrents via Telegram and pass to Transmission"
version: "0.1.11"
slug: tg2transmission
url: "https://github.com/alekslegkih/ha-addons/tree/main/tg2transmission"

image: ghcr.io/alekslegkih/tg2transmission-dev
arch:
  - amd64
  - aarch64

startup: application
boot: auto
init: false
homeassistant_api: true

map:
  - share:rw

schema:
  token: str?
  user_ids:
    - name: str?
      id: int?
  proxy:
    enabled: bool?
    type: list(socks|http)?
    host: str?
    port: port?
    username: str?
    password: password?
  transmission:
    host: str
    port: port?
    username: str?
    password: password?
    watch_folder: str?

options:
  token: ""
  user_ids: []
  proxy: {}
  transmission: {}
    port: 9091
    watch_folder: "/share/watch"
